name: Check Subscriptions
on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC

jobs:
  check-subscriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Call subscription check endpoint
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/cron/check-subscriptions \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
